### ISSUE TITLE
PWA not showing 

### ISSUE THREAD

**Issue by alekhakumarswain** [Parbeenmirza/Weather-App#1]
in manifest.json
  "start_url": "https://github.com/Parbeenmirza/Weather-App",
no need to add url of web site instead of only
 "start_url": "Parbeenmirza/Weather-App"
 
 in serviceworker.js change to
 const assetsToCache = [
  "/Parbeenmirza/Weather-App/styles.css",
  "/Parbeenmirza/Weather-App/app.js",
  "/Parbeenmirza/Weather-App/manifest.json",
  "/Parbeenmirza/Weather-App/index.html",
];

**Comment by Parbeenmirza** [comment]
ohki.. tq
